import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; //un comment to use tailwind
// import "bootstrap/dist/css/bootstrap.css";
import { AuthProvider } from "./providers/authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-800" style={{ height: "100%" }}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
